server:
  port: 8080
spring:
  application:
    name: greeting-service

  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: hml

greeting-service:
  greeting: "Hello"
  default-value: "World"

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

