server:
  port: 8888
spring:
  application:
    name: config-serve

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Alison8547/config-server
          default-label: main
          search-paths:
            - 'greeting-service*'
        #  username:
        # password:
